language: php

sudo: false

env:
  global:
    - setup=basic
matrix:
  include:
    - php: 7.2
      env: setup=stable
    - php: 7.3
      env: setup=stable
    - php: 7.4
      env: setup=stable
    - php: 8.0
      env: setup=stable

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi


script:
  - vendor/bin/phpunit
